version: "3.8"

services:
  jira-proxy:
    ports:
      - 80:80

  jira-frontend:
    ports:
      - 3000:3000

  jira-backend:
    command: catalina.sh jpda run
    ports:
      - 5005:5005
      - 8080:8080

  jira-database:
    ports:
      - 5431:5432
